apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-ha.master.fullname" . }}
  labels:
    {{- include "wordpress-ha.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: wordpress-master
  template:
    metadata:
      labels:
        app.kubernetes.io/component: wordpress-master
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.master.image.repository }}:{{ .Values.master.image.tag }}
          volumeMounts:
            - name: wp-data
              mountPath: /var/www/html
      volumes:
        - name: wp-data
          persistentVolumeClaim:
            claimName: {{ include "wordpress-ha.master.fullname" . }}-pvc
