apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-master
  labels:
    {{- include "wordpress-ha.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      role: master
      app.kubernetes.io/component: wordpress-master
  template:
    metadata:
      labels:
        role: master
        app.kubernetes.io/component: wordpress-master
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.master.image.repository }}:{{ .Values.master.image.tag }}
          volumeMounts:
            - name: wp-data
              mountPath: /var/www/html
        - name: rsync-sidecar
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache openssh rsync bash
              while true; do
                {{- $root := . }}
                {{- range $i, $_ := until (int $root.Values.slave.replicaCount) }}
                  rsync -avzp -e "ssh -p 2222 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa" --delete /var/www/html/wp-content/plugins/ root@{{ printf "%s-slave-%d.%s-headless.%s.svc.cluster.local" $root.Release.Name $i $root.Release.Name $root.Release.Namespace }}:/var/www/html/wp-content/plugins/
                  rsync -avzp -e "ssh -p 2222 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa" --delete /var/www/html/wp-content/themes/ root@{{ printf "%s-slave-%d.%s-headless.%s.svc.cluster.local" $root.Release.Name $i $root.Release.Name $root.Release.Namespace }}:/var/www/html/wp-content/themes/
                {{- end }}
                sleep 60
              done
          volumeMounts:
            - name: wp-data
              mountPath: /var/www/html
            - name: ssh-key
              mountPath: /root/.ssh/id_rsa
              subPath: id_rsa
              readOnly: true
      volumes:
        - name: wp-data
          persistentVolumeClaim:
            claimName: {{ include "wordpress-ha.fullname" . }}-pvc
        - name: ssh-key
          secret:
            secretName: {{ .Values.rsync.sshkeysSecretName }}
            items:
            - key: private_key
              path: id_rsa
