apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress-ha.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.master.storage.size }}
  storageClassName: {{ .Values.master.storage.storageClass }}
  