apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-slave
  labels:
    {{- include "wordpress-ha.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.slave.replicaCount }}
  serviceName: {{ include "wordpress-ha.slave.fullname" . }}-headless
  selector:
    matchLabels:
      app.kubernetes.io/component: wordpress-slave
      {{- include "wordpress-ha.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: wordpress-slave
        {{- include "wordpress-ha.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: wordpress-slave
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: wordpress
          image: {{ .Values.slave.image.repository }}:{{ .Values.slave.image.tag }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wp-data
              mountPath: /var/www/html
            - name: ssh-public-key
              mountPath: /root/.ssh/authorized_keys
              subPath: authorized_keys
              readOnly: true
      volumes:
        - name: ssh-public-key
          secret:
            secretName: {{ .Values.rsync.sshkeysSecretName }}
            items:
              - key: public_key
                path: authorized_keys
  volumeClaimTemplates:
    - metadata:
        name: wp-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.slave.storage.size }}
        storageClassName: {{ .Values.slave.storage.storageClass }}
