apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-master
  labels:
    app.kubernetes.io/component: wordpress-master
    {{- include "wp-scale.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wp-scale.labels" . | nindent 6 }}
      app.kubernetes.io/component: wordpress-master
  template:
    metadata:
      labels:
        {{- include "wp-scale.labels" . | nindent 8 }}
        app.kubernetes.io/component: wordpress-master
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: wordpress
          image: {{ .Values.master.image.repository }}:{{ .Values.master.image.tag }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: wp-data
              mountPath: /var/www/html
            - name: php-config-volume
              mountPath: /usr/local/etc/php/conf.d/customize.ini
              subPath: customize.ini
          envFrom:
            - secretRef:
                name: {{ .Values.wordpressCredentialSecret.name }}

        {{- if .Values.s3syncer.enabled }}
        - name: s3syncer
          image: {{ .Values.s3syncer.image.repository }}:{{ .Values.s3syncer.image.tag }}
          ports:
            - name: s3syncerhttp
              containerPort: {{ .Values.s3syncer.service.port }}
              protocol: TCP
          env:
            - name: S3_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.wordpressCredentialSecret.name }}
                  key: S3_KEY
            - name: S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.wordpressCredentialSecret.name }}
                  key: S3_SECRET
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.wordpressCredentialSecret.name }}
                  key: S3_BUCKET
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.wordpressCredentialSecret.name }}
                  key: S3_ENDPOINT
          volumeMounts:
            - name: wp-data
              mountPath: {{ .Values.s3syncer.mountPath }}
        {{- end }}

      volumes:
        - name: php-config-volume
          configMap:
            name: {{ .Release.Name }}-php-config
            items:
              - key: customize.ini
                path: customize.ini
        - name: wp-data
          persistentVolumeClaim:
            claimName: {{ include "wp-scale.fullname" . }}-pvc
