apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-master
  labels:
    {{- include "wp-scale.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      role: master
      app.kubernetes.io/component: wordpress-master
  template:
    metadata:
      labels:
        role: master
        app.kubernetes.io/component: wordpress-master
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.master.image.repository }}:{{ .Values.master.image.tag }}
          volumeMounts:
            - name: wp-data
              mountPath: /var/www/html/wp-content/plugins
              subPath: plugins
            - name: wp-data
              mountPath: /var/www/html/wp-content/themes
              subPath: themes
            - name: wp-config-volume
              mountPath: /var/www/html/wp-config.php
              subPath: wp-config.php
            - name: htaccess-volume
              mountPath: /var/www/html/.htaccess
              subPath: .htaccess
            - name: php-config-volume
              mountPath: /usr/local/etc/php/conf.d/customize.ini
              subPath: customize.ini
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.wordpressCredentialSecret.name }}

        {{- if .Values.rsync.enabled }}
        - name: rsync-sidecar
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache openssh rsync bash
              while true; do
                {{- $root := . }}
                {{- range $i, $_ := until (int $root.Values.slave.replicaCount) }}
                  rsync -avzp -e "ssh -p 2222 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa" --delete /var/www/html/wp-content/plugins/ root@{{ printf "%s-slave-%d.%s-headless.%s.svc.cluster.local" $root.Release.Name $i $root.Release.Name $root.Release.Namespace }}:/var/www/html/wp-content/plugins/
                  rsync -avzp -e "ssh -p 2222 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa" --delete /var/www/html/wp-content/themes/ root@{{ printf "%s-slave-%d.%s-headless.%s.svc.cluster.local" $root.Release.Name $i $root.Release.Name $root.Release.Namespace }}:/var/www/html/wp-content/themes/
                {{- end }}
                sleep 60
              done
          volumeMounts:
            - name: wp-data
              mountPath: /var/www/html
            - name: ssh-key
              mountPath: /root/.ssh/id_rsa
              subPath: id_rsa
              readOnly: true
      {{- end }}
      volumes:
        - name: php-config-volume
          configMap:
            name: {{ .Release.Name }}-php-config
            items:
              - key: customize.ini
                path: customize.ini
        - name: wp-config-volume
          configMap:
            name: {{ include "wp-scale.fullname" . }}-wp-config
            items:
              - key: wp-config.php
                path: wp-config.php
        - name: htaccess-volume
          configMap:
            name: {{ include "wp-scale.fullname" . }}-htaccess
            items:
              - key: htaccess
                path: .htaccess
        - name: wp-data
          persistentVolumeClaim:
            claimName: {{ include "wp-scale.fullname" . }}-pvc
        {{- if .Values.rsync.enabled }}
        - name: ssh-key
          secret:
            secretName: {{ .Values.rsync.sshkeysSecretName }}
            items:
            - key: private_key
              path: id_rsa
        {{- end }}
