{{- if .Values.phpmyadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-phpmyadmin
  labels:
    app: phpmyadmin
    {{- include "wp-scale.labels" . | nindent 4 }}
    component: phpmyadmin
spec:
  replicas: 1
  selector:
    {{- include "wp-scale.selectorLabels" . | nindent 4 }}
    component: phpmyadmin
    matchLabels:
      app: phpmyadmin
      component: phpmyadmin
      {{- include "wp-scale.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: phpmyadmin
        component: phpmyadmin
        {{- include "wp-scale.selectorLabels" . | nindent 8 }}
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
{{- end }}
      containers:
        - name: phpmyadmin
          image: phpmyadmin
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: '{{ .Release.Name }}-mysql:3306'

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-phpmyadmin
  labels:
    {{- include "wp-scale.labels" . | nindent 4 }}
    component: phpmyadmin
spec:
  type: ClusterIP
  selector:
    {{- include "wp-scale.selectorLabels" . | nindent 4 }}
    component: phpmyadmin
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-phpmyadmin-ingress
  labels:
    {{- include "wp-scale.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
#  tls:
#    - hosts:
#        - {{ .Values.phpmyadmin.phpmyadminHost }}
#      secretName: tls-secret
  rules:
    - host: {{ .Values.phpmyadmin.phpmyadminHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-phpmyadmin
                port:
                  name: http

{{- end }}
