apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wp-scale.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.master.storage.size }}
  storageClassName: {{ .Values.master.storage.storageClass }}
  