apiVersion: v1
kind: Service
metadata:
  name: {{ include "wp-scale.fullname" . }}-master
  labels:
    role: master
    {{- include "wp-scale.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    role: master
    {{- include "wp-scale.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http