apiVersion: v1
kind: Service
metadata:
  name: {{ include "wp-scale.fullname" . }}-slave
  labels:
    role: slave
    {{- include "wp-scale.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    role: slave
    {{- include "wp-scale.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http