apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-slave
  labels:
    role: slave
    app.kubernetes.io/component: wordpress-slave
    {{- include "wp-scale.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.slave.replicaCount }}
  serviceName: {{ include "wp-scale.fullname" . }}-slave
  selector:
    matchLabels:
      role: slave
      app.kubernetes.io/component: wordpress-slave
      {{- include "wp-scale.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        role: slave
        app.kubernetes.io/component: wordpress-slave
        {{- include "wp-scale.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: wordpress-slave
                topologyKey: "kubernetes.io/hostname"
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}

      containers:
        - name: wordpress
          image: {{ .Values.slave.image.repository }}:{{ .Values.slave.image.tag }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            {{- if .Values.slave.storage.enabled }}
            - name: wp-data
              mountPath: /var/www/html/
            {{- end }}
            - name: php-config-volume
              mountPath: /usr/local/etc/php/conf.d/customize.ini
              subPath: customize.ini
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.wordpressCredentialSecret.name }}

      volumes:
        - name: php-config-volume
          configMap:
            name: {{ .Release.Name }}-php-config
            items:
              - key: customize.ini
                path: customize.ini
  {{- if .Values.slave.storage.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: wp-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.slave.storage.size }}
        storageClassName: {{ .Values.slave.storage.storageClass }}
  {{- end }}
